# Generated by Django 5.1.6 on 2025-02-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.CharField(max_length=50),
        ),
    ]
