# Generated by Django 5.1.6 on 2025-03-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0003_recipe_created_on_recipe_updated_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="author",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="created_on",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="updated_on",
        ),
    ]
