# Generated by Django 5.1.6 on 2025-03-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0005_recipe_author_recipe_created_on_recipe_updated_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="author",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
