# Generated by Django 5.1.6 on 2025-03-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0006_alter_recipe_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
